language: rust
os:
    - linux
    - osx
    - windows
rust:
    - stable
    - nightly
install:
    rustup component add rustfmt
matrix:
    fast_finish: true
script:
    - cargo build
    - cargo test
notifications:
    email: false
