sudo: required
language: rust
cache: cargo
addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
        sources:
            - kalakris-cmake
os:
    - linux
    - osx
    - windows
rust:
    - stable
    - nightly
install:
    rustup component add rustfmt
matrix:
    fast_finish: true
before_script:
    if: os = linux
    - export PATH=$HOME/.cargo/bin:$PATH
    - cargo install -f cargo-travis
script:
    - cargo build
    - cargo test
after_success:
    if: os = linux
    - cargo coveralls
notifications:
    email: false
